name       : pybind11
version    : 2.9.2
release    : 5
source     :
    - https://github.com/pybind/pybind11/archive/refs/tags/v2.9.2.tar.gz : 6bd528c4dbe2276635dc787b6b1f2e5316cf6b49ee3e150264e455a0d68d19c1
license    : BSD-3-Clause
component  : programming.python
summary    : Seamless operability between C++11 and Python
description: |
    pybind11 is a lightweight header-only library that exposes C++ types in Python and vice versa, mainly to create Python bindings of existing C++ code.
patterns   :
    - /usr/include
    - /usr/share
builddeps  :
    - pkgconfig(eigen3)  # For test
    - pkgconfig(python3)
    - libboost-devel
    - numpy              # For test
    - python-pytest
    - scipy              # For test
setup      : |
    mkdir -p build && pushd build
    %cmake ..
    popd
build      : |
    %python3_setup
    %make -C build
install    : |
    %python3_install
    %make_install -C build
    rm -rfv $installdir/usr/include/python3.*
check      : |
    pushd pybind11-%version%/build
    %make check
    popd
